---
- name: config_openldap | configuring ldap
  template:
    src: "etc/ldap/ldap.conf.j2"
    dest: "/etc/ldap/ldap.conf"
    owner: root
    group: root
    mode: 0644

- name: config_openldap | configuring phpldapadmin
  template:
    src: "etc/phpldapadmin/config.php.j2"
    dest: "/etc/phpldapadmin/config.php"
    owner: root
    group: www-data
    mode: 0640

- name: config_openldap | creating database population config
  template:
    src: "etc/ldap/slapd.d/populate_content.ldif.j2"
    dest: "/etc/ldap/slapd.d/populate_content.ldif"
    owner: root
    group: root
    mode: 0640

- name: Make sure we have a parent entry for users
  ldap_entry:
    dn: ou=People,dc=lanathome,dc=com
    objectClass: organizationalUnit
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Make sure we have a parent entry for groups
  ldap_entry:
    dn: ou=Groups,dc=lanathome,dc=com
    objectClass:
      - organizationalUnit
      - top
    attributes:
      ou: Groups
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create saunix group
  ldap_entry:
    dn: cn=saunix,ou=Groups,dc=lanathome,dc=com
    objectClass:
      - posixGroup
    attributes:
      cn: saunix
      gidnumber: 5001
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create dba group
  ldap_entry:
    dn: cn=dba,ou=Groups,dc=lanathome,dc=com
    objectClass:
      - posixGroup
    attributes:
      cn: saunix
      gidnumber: 5001
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create middleware group
  ldap_entry:
    dn: cn=middleware,ou=Groups,dc=lanathome,dc=com
    objectClass:
      - posixGroup
    attributes:
      cn: saunix
      gidnumber: 5001
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create user ngr
  ldap_entry:
    dn: uid=ngr,ou=People,dc=lanathome,dc=com
    objectClass:
      - inetOrgPerson
      - posixAccount
      - shadowAccount
    attributes:
      cn: ngr
      displayname: Aurelien Grosshans
      gecos: Aurelien Grosshans
      gidnumber: 5001
      givenname: Aurelien
      homedirectory: /home/ngr
      loginshell: /bin/bash
      sn: Grosshans
      uid: ngr
      uidnumber: 10001
      userpassword: changeme
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create user mly
  ldap_entry:
    dn: uid=mly,ou=People,dc=lanathome,dc=com
    objectClass:
      - inetOrgPerson
      - posixAccount
      - shadowAccount
    attributes:
      cn: myl
      displayname: Marie-Laure Leroy
      gecos: Marie-Laure Leroy
      gidnumber: 5001
      givenname: Marie-Laure
      homedirectory: /home/mly
      loginshell: /bin/bash
      sn: Leroy
      uid: mly
      uidnumber: 10002
      userpassword: changeme
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create user mgr
  ldap_entry:
    dn: uid=mgr,ou=People,dc=lanathome,dc=com
    objectClass:
      - inetOrgPerson
      - posixAccount
      - shadowAccount
    attributes:
      cn: mgr
      displayname: Maxime Grosshans
      gecos: Maxime Grosshans
      gidnumber: 5002
      givenname: Maxime
      homedirectory: /home/mgr
      loginshell: /bin/bash
      sn: Grosshans
      uid: mgr
      uidnumber: 10003
      userpassword: changeme
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create user lgr
  ldap_entry:
    dn: uid=lgr,ou=People,dc=lanathome,dc=com
    objectClass:
      - inetOrgPerson
      - posixAccount
      - shadowAccount
    attributes:
      cn: lgr
      displayname: Louise Grosshans
      gecos: Louise Grosshans
      gidnumber: 5004
      givenname: Louise
      homedirectory: /home/lgr
      loginshell: /bin/bash
      sn: Grosshans
      uid: lgr
      uidnumber: 10004
      userpassword: changeme
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Config TLS - gnutls-bin package install
  apt:
    name: gnutls-bin
    state: present

- name: Config TLS - ssl-cert package install
  apt:
    name: ssl-cert
    state: present

- name: Config TLS - import cakey.pem
  copy:
    src: files/cakey.pem
    dest: /etc/ssl/private/cakey.pem
    owner: root
    group: root
    mode: 0644

- name: Config TLS - import ca.info
  copy:
    src: files/ca.info
    dest: /etc/ssl/ca.info
    owner: root
    group: root
    mode: 0644

- name: Config TLS - import auto-signed certificate
  copy:
    src: files/cacert.pem
    dest: /etc/ssl/certs/cacert.pem
    owner: root
    group: root
    mode: 0644

- name: Config TLS - import private key
  copy:
    src: files/ldap01_slapd_key.pem
    dest: /etc/ssl/private/ldap01_slapd_key.pem
    owner: root
    group: root
    mode: 0640

- name: Config TLS - import ldap01.info
  copy:
    src: files/ldap01.info
    dest: /etc/ssl/ldap01.info
    owner: root
    group: root
    mode: 0644

- name: Config TLS - create the certificate
  shell: certtool --generate-certificate --load-privkey /etc/ssl/private/ldap01_slapd_key.pem --load-ca-certificate /etc/ssl/certs/cacert.pem --load-ca-privkey /etc/ssl/private/cakey.pem --template /etc/ssl/ldap01.info --outfile /etc/ssl/certs/ldap01_slapd_cert.pem

- name: Config TLS - create ssl-cert group
  group:
    name: ssl-cert
    gid: 115
    state: present

- name: Config TLS - 
  user: 
    name: openldap
    groups: ssl-cert
    append: yes

- name: Config TLS - Adjust permissions and ownership
  file:
    path: /etc/ssl/private/ldap01_slapd_key.pem
    owner: root
    group: openldap
    mode: 0640

- name: Config TLS - import certinfo.ldif
  copy:
    src: files/certinfo.ldif
    dest: /etc/ldap/certinfo.ldif
    owner: root
    group: root
    mode: 0644

- name: Config TLS - import ldap.conf
  copy:
    src: files/ldap.conf
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: 0644

- name: Config TLS - finally modify openldap to include TLS
  shell: sudo ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/certinfo.ldif
  ignore_errors: yes 
  
- name: Config TLS - restart openldap
  service:
    name: slapd
    state: restarted

- name: Config Sudo - Import sudo schema in openldap
  copy:
    src: files/sudo.ldif
    dest: /etc/ldap/schema/sudo.ldif
    owner: root
    group: root
    mode: 0644

- name: Import sudo schema in openldap
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/sudo.ldif

- name: Config Sudo - restart openldap
  service:
    name: slapd
    state: restarted

- name: Create SUDOers
  ldap_entry:
    dn: ou=SUDOers,dc=lanathome,dc=com
    objectClass: 
      - top
      - organizationalUnit
    attributes:    
      ou: SUDOers
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create sudoOption
  ldap_entry:
    dn: cn=defaults,ou=SUDOers,dc=lanathome,dc=com
    objectClass:
      - top
      - sudoRole
    attributes:
      cn: defaults
      description: Default sudoOption's go here
      sudoOption: requiretty
      sudoOption: env_reset
      sudoOption: env_keep = "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS_XKB_CHARSET XAUTHORITY"
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create cn=root,ou=SUDOers,dc=lanathome,dc=com
  ldap_entry:
    dn: cn=root,ou=SUDOers,dc=lanathome,dc=com
  objectClass:
    - top
    - sudoRole
  attributes:
    cn: root
    sudoUser: root
    sudoHost: ALL
    sudoRunas: ALL
    sudoCommand: ALL
  server_uri:   ldapi:///localhost
  bind_dn: "{{ openldap_bind_id }}"
  bind_pw: "{{ openldap_admin_password }}"
  state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create cn=ADMINS,ou=SUDOers,dc=lanathome,dc=com
  ldap_entry:
    dn: cn=ADMINS,ou=SUDOers,dc=lanathome,dc=com
  objectClass:
    - top
    - sudoRole
  attributes:
    cn: ADMINS
    sudoUser: testuser
    sudoHost: ALL
    sudoRunas: ALL
    sudoCommand: ALL
  server_uri:   ldapi:///localhost
  bind_dn: "{{ openldap_bind_id }}"
  bind_pw: "{{ openldap_admin_password }}"
  state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate