---

- name: Create SUDOers
  ldap_entry:
    dn: ou=SUDOers,dc=lanathome,dc=com
    objectClass: 
      - top
      - organizationalUnit
    attributes:    
      ou: SUDOers
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create sudoOption
  ldap_entry:
    dn: cn=defaults,ou=SUDOers,dc=lanathome,dc=com
    objectClass:
      - top
      - sudoRole
    attributes:
      cn: defaults
      description: Default sudoOption's go here
      sudoOption: requiretty
      sudoOption: env_reset
      sudoOption: env_keep = "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS_XKB_CHARSET XAUTHORITY"
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create cn=defaults,ou=SUDOers,dc=lanathome,dc=com
  ldap_entry:
  # sudo defaults
    dn: cn=defaults,ou=SUDOers,dc=lanathome,dc=com
  objectClass:
    - top
    - sudoRole
  attributes: 
    cn: defaults
    description: Default sudoOptions go here
    sudoOption: env_keep+=SSH_AUTH_SOCK
  server_uri:   ldapi:///localhost
  bind_dn: "{{ openldap_bind_id }}"
  bind_pw: "{{ openldap_admin_password }}"
  state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: Create cn=%wheel,ou=SUDOers,dc=example,dc=com
  ldap_entry:
  # sudo defaults
    dn: cn=%wheel,ou=SUDOers,dc=example,dc=com
  objectClass:
    - top
    - sudoRole
  attributes: 
    cn: %wheel
    sudoUser: %wheel
    sudoHost: ALL
    sudoCommand: ALL
  server_uri:   ldapi:///localhost
  bind_dn: "{{ openldap_bind_id }}"
  bind_pw: "{{ openldap_admin_password }}"
  state: present
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate