---

- name: config_sudoers.yml | Import sudo.schema
  template:
    src: "etc/ldap/sudo.schema"
    dest: "/etc/ldap/schema/sudo.schema"
    owner: openldap
    group: openldap
    mode: 0640

- name: config_sudoers.yml | Import cn={0}sudo.ldif
  template:
    src: "etc/ldap/cn={0}sudo.ldif"
    dest: "/tmp/ldif_output/cn=config/cn=schema/cn={0}sudo.ldif"
    owner: openldap
    group: openldap
    mode: 0640

- name: config_sudoers.yml | Add sudo schema in ldap config
  shell: 'ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ldif_output/cn=config/cn=schema/cn={0}sudo.ldif'
  ignore_errors: yes  #set to get around erroring out that items already exist

- name: config_sudoers.yml | creating database population config
  template:
    src: "etc/ldap/slapd.d/populate_sudoers.ldif.j2"
    dest: "/etc/ldap/slapd.d/populate_sudoers.ldif"
    owner: openldap
    group: openldap
    mode: 0640

- name: config_sudoers.yml | Create ou=SUDOers,dc=lanathome,dc=com
  ldap_entry:
    dn: ou=SUDOers,dc=lanathome,dc=com
    objectClass: 
      - top
      - organizationalUnit
    attributes:    
      ou: SUDOers
    server_uri:   ldapi:///localhost
    bind_dn: "{{ openldap_bind_id }}"
    bind_pw: "{{ openldap_admin_password }}"
    state: present
    start_tls: yes
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate

- name: config_sudoers.yml | populating SUDOers
  shell: 'ldapadd -x -D {{ openldap_bind_id }} -w {{ openldap_admin_password }} -f /etc/ldap/slapd.d/populate_sudoers.ldif'
  ignore_errors: yes  #set to get around erroring out that items already exist
  when: >
        openldap_populate is defined and
        openldap_populate